language: node_js
node_js:
  - "10"
  - "12"
cache: yarn
script:
  - npm run test
branches:
  only:
  - master
after_success: npm run coverage
notifications:
  email:
    recipients:
      - swzyocowboy@icloud.com
    on_success: never
    on_failure: always
